use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

/// Number of primes to include (must be >= 54 for cfx_factor_u64)
const PRIMES_COUNT: usize = 1000;

fn generate_primes_c(primes_txt: &PathBuf, out_c: &PathBuf) {
    let content = fs::read_to_string(primes_txt).expect("Failed to read primes.txt");
    let primes: Vec<&str> = content
        .split(|c: char| c.is_whitespace() || c == ',')
        .filter(|s| !s.is_empty())
        .take(PRIMES_COUNT)
        .collect();

    let mut out = fs::File::create(out_c).expect("Failed to create primes.c");
    writeln!(out, "/* Auto-generated by build.rs. Do not edit. */").unwrap();
    writeln!(out, "#include \"cfx/primes.h\"\n").unwrap();
    writeln!(out, "const uint32_t cfx_primes[] = {{").unwrap();
    writeln!(out, "    {}", primes.join(", ")).unwrap();
    writeln!(out, "}};\n").unwrap();
    writeln!(out, "const size_t cfx_primes_len = {}u;", primes.len()).unwrap();
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let cfx_root = manifest_dir.parent().unwrap().parent().unwrap();
    let include_dir = cfx_root.join("include");
    let src_dir = cfx_root.join("src");
    let data_dir = cfx_root.join("data");

    // Generate primes.c from primes.txt
    let primes_txt = data_dir.join("primes.txt");
    let primes_c = out_dir.join("primes.c");
    generate_primes_c(&primes_txt, &primes_c);

    // Compile the C library
    let mut build = cc::Build::new();
    build
        .include(&include_dir)
        .files(&[
            // big/
            src_dir.join("big/big.c"),
            src_dir.join("big/ntt.c"),
            // math/
            src_dir.join("math/algo.c"),
            src_dir.join("math/fac.c"),
            // core/
            src_dir.join("core/vec.c"),
            // rng/
            src_dir.join("rng/rand.c"),
            // crypto/
            src_dir.join("crypto/chacha20.c"),
            src_dir.join("crypto/poly1305.c"),
            src_dir.join("crypto/aead_chacha20_poly1305.c"),
            src_dir.join("crypto/sha256.c"),
            src_dir.join("crypto/sha512.c"),
            src_dir.join("crypto/sha3.c"),
            src_dir.join("crypto/blake2.c"),
            src_dir.join("crypto/siphash.c"),
            src_dir.join("crypto/fe25519.c"),
            src_dir.join("crypto/ge25519.c"),
            src_dir.join("crypto/sc25519.c"),
            src_dir.join("crypto/x25519.c"),
            src_dir.join("crypto/ed25519.c"),
            src_dir.join("crypto/base64.c"),
            // generated
            primes_c,
        ])
        .flag_if_supported("-std=c99")
        .flag_if_supported("-O2")
        // Silence some warnings in C code when compiling as part of Rust build
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-sign-compare");

    build.compile("cfx");

    println!("cargo:rerun-if-changed={}", src_dir.display());
    println!("cargo:rerun-if-changed={}", include_dir.display());

    // Generate bindings if feature enabled
    #[cfg(feature = "regenerate-bindings")]
    {
        let bindings = bindgen::Builder::default()
            .header(include_dir.join("cfx/cfx.h").to_str().unwrap())
            .clang_arg(format!("-I{}", include_dir.display()))
            .allowlist_function("cfx_.*")
            .allowlist_type("cfx_.*")
            .allowlist_var("CFX_.*")
            .generate_comments(true)
            .derive_debug(true)
            .derive_default(true)
            .generate()
            .expect("Unable to generate bindings");

        let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
        bindings
            .write_to_file(out_path.join("bindings.rs"))
            .expect("Couldn't write bindings!");
    }
}
