#!/usr/bin/env python3
"""
Poly1271 reference implementation in Python for verification.
Uses Python's arbitrary precision integers - slow but obviously correct.
"""

M127 = (1 << 127) - 1  # Mersenne prime 2^127 - 1

def clamp_r(r_bytes):
    """Apply Poly1271 key clamping."""
    r = bytearray(r_bytes)
    r[3]  &= 0x0F
    r[7]  &= 0x0F
    r[11] &= 0x0F
    r[15] &= 0x07  # clears bit 127
    r[4]  &= 0xFC
    r[8]  &= 0xFC
    r[12] &= 0xFC
    return bytes(r)

def le_bytes_to_int(b):
    """Little-endian bytes to integer."""
    return int.from_bytes(b, 'little')

def int_to_le_bytes(n, length):
    """Integer to little-endian bytes."""
    return n.to_bytes(length, 'little')

def poly1271(message, key):
    """
    Compute Poly1271 MAC.

    Args:
        message: bytes
        key: 32 bytes (r[0:16], s[16:32])

    Returns:
        16-byte tag
    """
    assert len(key) == 32

    # Split and clamp key
    r_bytes = clamp_r(key[0:16])
    s_bytes = key[16:32]

    r = le_bytes_to_int(r_bytes)
    s = le_bytes_to_int(s_bytes)

    # Ensure r < 2^127 (should be guaranteed by clamping)
    assert r < (1 << 127), f"r too large: {r.bit_length()} bits"

    # Process message in 15-byte blocks
    h = 0
    block_size = 15

    for i in range(0, len(message), block_size):
        block = message[i:i+block_size]

        # Pad block: append 0x01
        padded = block + b'\x01'

        # Convert to integer (little-endian)
        n = le_bytes_to_int(padded)

        # h = (h + block) * r mod M127
        h = (h + n) % M127
        h = (h * r) % M127

    # Final tag = (h + s) mod 2^128
    tag_int = (h + s) % (1 << 128)

    return int_to_le_bytes(tag_int, 16)

def test_vector(name, key_hex, msg_hex, expected_tag_hex):
    """Test a single vector."""
    key = bytes.fromhex(key_hex)
    msg = bytes.fromhex(msg_hex) if msg_hex else b''
    expected = bytes.fromhex(expected_tag_hex)

    result = poly1271(msg, key)

    if result == expected:
        print(f"PASS {name}: {result.hex()}")
        return True
    else:
        print(f"FAIL {name}")
        print(f"  Expected: {expected.hex()}")
        print(f"  Got:      {result.hex()}")
        return False

def generate_test_vectors():
    """Generate additional test vectors for validation."""
    import hashlib

    vectors = []

    # Deterministic key generation from seed
    def make_key(seed):
        h = hashlib.sha256(seed.encode()).digest()
        return h

    # Test various lengths around block boundaries
    lengths = [0, 1, 7, 14, 15, 16, 29, 30, 31, 44, 45, 46, 100, 255, 256, 1000]

    for length in lengths:
        key = make_key(f"key_for_len_{length}")
        msg = bytes([(i * 7 + 13) & 0xFF for i in range(length)])
        tag = poly1271(msg, key)

        vectors.append({
            'name': f'len_{length}',
            'key': key.hex(),
            'msg': msg.hex(),
            'tag': tag.hex(),
            'msg_len': length
        })

    return vectors

def main():
    print("=" * 60)
    print("Poly1271 Python Reference Implementation")
    print("=" * 60)
    print()

    # Test vectors from the C unit tests
    print("Verifying C unit test vectors:")
    print("-" * 40)

    all_passed = True

    # Empty message
    all_passed &= test_vector(
        "empty",
        "0102030405060708090a0b0c0d0e0f10" + "1112131415161718191a1b1c1d1e1f20",
        "",
        "1112131415161718191a1b1c1d1e1f20"
    )

    # Single block "Hello, Poly127\0" (15 bytes including null terminator)
    # H  e  l  l  o  ,     P  o  l  y  1  2  7  \0
    # 48 65 6c 6c 6f 2c 20 50 6f 6c 79 31 32 37 00 = 15 bytes
    all_passed &= test_vector(
        "single_block",
        "000102030405060708090a0b0c0d0e0f" + "101112131415161718191a1b1c1d1e1f",
        "48656c6c6f2c20506f6c793132370" + "0",  # 15 bytes
        "44e9b6e7abf4d5a45e07f3d83178ea1f"
    )

    # Multiple blocks (100 bytes: 0x00..0x63)
    msg_100 = ''.join(f'{i:02x}' for i in range(100))
    key_100 = ''.join(f'{(i*3+7)&0xff:02x}' for i in range(32))
    all_passed &= test_vector(
        "multi_block_100",
        key_100,
        msg_100,
        "c79db66d6682ce7f1ea6662144fa29b2"
    )

    print()
    print("=" * 60)
    print("Generating additional test vectors:")
    print("=" * 60)
    print()

    vectors = generate_test_vectors()

    print("// Additional test vectors for poly1271 (generated by Python reference)")
    print("// Format: {msg_len, key_hex, msg_pattern, expected_tag_hex}")
    print()

    for v in vectors:
        print(f"// Length {v['msg_len']}:")
        print(f"//   Key: {v['key']}")
        if v['msg_len'] <= 32:
            print(f"//   Msg: {v['msg']}")
        else:
            print(f"//   Msg: {v['msg'][:32]}... ({v['msg_len']} bytes)")
        print(f"//   Tag: {v['tag']}")
        print()

    print("=" * 60)
    if all_passed:
        print("All verification tests PASSED")
    else:
        print("Some tests FAILED!")
    print("=" * 60)

    return all_passed

if __name__ == '__main__':
    import sys
    sys.exit(0 if main() else 1)
