set(WARNINGS "-Wall -Wextra -Wpedantic")
set(SILENCED "-Wno-gnu-zero-variadic-macro-arguments")

# set(EMERGENCY "-fno-strict-aliasing -fno-omit-frame-pointer -g")
# set(EMERGENCY "-fsanitize=address,undefined -fno-omit-frame-pointer -g")

string(APPEND CMAKE_C_FLAGS_DEBUG          " -g -DCFX_DEBUG ${WARNINGS} ${SILENCED}")
string(APPEND CMAKE_C_FLAGS_RELEASE        " -O3 -DNDEBUG -mbmi2 -madx ${WARNINGS} ${SILENCED}")
string(APPEND CMAKE_C_FLAGS_RELWITHDEBINFO " -O2 -g -DNDEBUG -DCFX_DEBUG ${WARNINGS} ${SILENCED}")

message(STATUS "Build type: ${CMAKE_BUILD_TYPE}")
if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "Flags: ${CMAKE_C_FLAGS_DEBUG}")
elseif (CMAKE_BUILD_TYPE STREQUAL "Release")
    message(STATUS "Flags: ${CMAKE_C_FLAGS_RELEASE}")
elseif (CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    message(STATUS "Flags: ${CMAKE_C_FLAGS_RELWITHDEBINFO}")
else()
    message(STATUS "Unknown build type" )
endif()