
function(cfx_generate_primes PRIMES_TXT OUT_C PRIMES_COUNT)

    file(READ "${PRIMES_TXT}" CFX_PRIMES_TXT)

    string(REGEX REPLACE "[, \t\r\n]+" ";" CFX_PRIMES_LIST "${CFX_PRIMES_TXT}")
    list(REMOVE_ITEM CFX_PRIMES_LIST "")  # drop empties just in case

    list(LENGTH CFX_PRIMES_LIST CFX_PRIMES_TOTAL)
    if (PRIMES_COUNT GREATER CFX_PRIMES_TOTAL)
        message(FATAL_ERROR
            "CFX_PRIMES_COUNT (${PRIMES_COUNT}) > total primes (${CFX_PRIMES_TOTAL})")
    endif()

    # there are 54 primes < 255
    if (PRIMES_COUNT LESS 54)
        message(FATAL_ERROR
            "CFX_PRIMES_COUNT (${PRIMES_COUNT}) < 54 — "
            "this breaks cfx_factor_u64 (requires first 54 primes (all 1 byte primes))")
    endif()

    message(STATUS "CFX_PRIMES_COUNT ${PRIMES_COUNT}")

    list(SUBLIST CFX_PRIMES_LIST 0 ${PRIMES_COUNT} CFX_PRIMES_USED)
    string(JOIN ", " CFX_PRIMES_INIT ${CFX_PRIMES_USED})

    file(WRITE "${OUT_C}" "/* Auto-generated by CMake. Do not edit. */\n")
    file(APPEND "${OUT_C}" "#include \"cfx/primes.h\"\n\n")
    file(APPEND "${OUT_C}" "const uint32_t cfx_primes[] = {\n    ${CFX_PRIMES_INIT}\n};\n\n")
    file(APPEND "${OUT_C}" "const size_t cfx_primes_len = ${PRIMES_COUNT}u;\n")

    # Export path back to caller
    set(CFX_PRIMES_GENERATED_SRC "${OUT_C}" PARENT_SCOPE)
endfunction()
